<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Owner-PC" name="sjcswank.com.guthub.seleniumTests.LoginTests" tests="6" failures="1" timestamp="24 May 2019 18:27:54 GMT" time="223.579" errors="0">
  <testcase name="testCase01" time="43.000" classname="sjcswank.com.guthub.seleniumTests.LoginTests">
    <failure type="org.junit.ComparisonFailure" message="expected:&lt;Incorrect [Username]&gt; but was:&lt;Incorrect [Password]&gt;">
      <![CDATA[org.junit.ComparisonFailure: expected:<Incorrect [Username]> but was:<Incorrect [Password]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at sjcswank.com.guthub.seleniumTests.LoginTests.testCase01(LoginTests.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testCase01 -->
  <testcase name="testCase01" time="12.941" classname="sjcswank.com.guthub.seleniumTests.LoginTests"/>
  <testcase name="testCase01" time="42.467" classname="sjcswank.com.guthub.seleniumTests.LoginTests"/>
  <testcase name="testCase01" time="41.378" classname="sjcswank.com.guthub.seleniumTests.LoginTests"/>
  <testcase name="testCase01" time="41.780" classname="sjcswank.com.guthub.seleniumTests.LoginTests"/>
  <testcase name="testCase01" time="42.013" classname="sjcswank.com.guthub.seleniumTests.LoginTests"/>
</testsuite> <!-- sjcswank.com.guthub.seleniumTests.LoginTests -->
